# cloud.yaml

# Cloud provider information (Google Cloud)
cloud:
  provider: gcp

# Database service configuration (Google Cloud SQL - MySQL)
database:
  name: db
  engine: mysql
  instance_type: db-n1-standard-1
  storage_size: 10GB
  region: us-central1
  # Add other Google Cloud SQL specific configuration options as needed

# Steps for Cloud Build
steps:
  # This step will build and push the new container image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/blood', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/blood']

  # This step will deploy the new container image to Google Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'blood', '--image=gcr.io/$PROJECT_ID/blood', '--region=europe-west2', '--allow-unauthenticated']
