# Generated by Django 4.2.4 on 2023-10-27 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_blood_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blood',
        ),
    ]
