# Generated by Django 4.2.4 on 2023-10-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_confirmrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(null=True)),
            ],
        ),
    ]
