# Generated by Django 4.2.4 on 2023-10-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hospital_hospitalname_blood'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confirmrequest',
        ),
    ]
