# Generated by Django 4.2.4 on 2023-10-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_confirmrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Confirmrequest',
        ),
    ]
