# Generated by Django 4.2.4 on 2023-10-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_confirmrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('bloodgroup', models.CharField(choices=[('A+', 'a+'), ('A-', 'a-'), ('B-', 'b-'), ('B+', 'b+'), ('O+', 'o+'), ('O-', 'o-'), ('AB+', 'ab+'), ('AB-', 'ab-')], max_length=5)),
                ('accept', models.BooleanField(null=True)),
            ],
        ),
    ]
